const express=require("express"),sqlite3=require("sqlite3").verbose(),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),cors=require("cors"),path=require("path");
const app=express(),PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET||"collegehub-demo-secret-change-me";
app.use(cors());app.use(express.json());
const db=new sqlite3.Database(process.env.DB_PATH||path.join(__dirname,"collegehub.db"));
db.serialize(()=>{db.run("CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE,password TEXT)");
db.run("CREATE TABLE IF NOT EXISTS students(id INTEGER PRIMARY KEY AUTOINCREMENT,student_code TEXT UNIQUE,name TEXT,email TEXT,department TEXT,year INTEGER,status TEXT)");
db.run("INSERT OR IGNORE INTO users(username,password) VALUES('admin',?)",[bcrypt.hashSync("admin123",10)]);
db.get("SELECT COUNT(*) count FROM students",(e,r)=>{if(!e&&r.count===0){let s=db.prepare("INSERT INTO students(student_code,name,email,department,year,status) VALUES(?,?,?,?,?,?)");[
["CH2026001","Arun Kumar","arun@example.com","Computer Science",4,"Active"],["CH2026002","Priya Sharma","priya@example.com","Information Technology",3,"Active"],["CH2026003","Rahul Das","rahul@example.com","Electronics",2,"Active"],["CH2026004","Meena Raj","meena@example.com","Computer Science",1,"Active"],["CH2026005","Vijay Anand","vijay@example.com","Business Administration",3,"Inactive"]].forEach(x=>s.run(x));s.finalize()}})});
app.get("/api/health",(q,r)=>r.json({status:"healthy",service:"collegehub-backend",server:"private-ec2"}));
app.post("/api/login",(q,r)=>{let{username,password}=q.body;db.get("SELECT * FROM users WHERE username=?",[username],(e,u)=>{if(e||!u||!bcrypt.compareSync(password||"",u.password))return r.status(401).json({message:"Invalid username or password"});r.json({token:jwt.sign({id:u.id,username:u.username},SECRET,{expiresIn:"2h"})})})});
function auth(q,r,n){let h=q.headers.authorization||"",t=h.startsWith("Bearer ")?h.slice(7):null;if(!t)return r.status(401).json({message:"Authentication required"});try{q.user=jwt.verify(t,SECRET);n()}catch(e){r.status(401).json({message:"Invalid or expired token"})}}
app.get("/api/students",auth,(q,r)=>db.all("SELECT * FROM students ORDER BY id DESC",(e,x)=>e?r.status(500).json({message:"Database error"}):r.json(x)));
app.post("/api/students",auth,(q,r)=>{let{x}=q.body,{student_code,name,email,department,year,status}=q.body;if(!student_code||!name||!email||!department||!year)return r.status(400).json({message:"Required fields missing"});db.run("INSERT INTO students(student_code,name,email,department,year,status) VALUES(?,?,?,?,?,?)",[student_code,name,email,department,year,status||"Active"],function(e){if(e)return r.status(400).json({message:"Student ID may already exist"});r.status(201).json({id:this.lastID})})});
app.put("/api/students/:id",auth,(q,r)=>{let{student_code,name,email,department,year,status}=q.body;db.run("UPDATE students SET student_code=?,name=?,email=?,department=?,year=?,status=? WHERE id=?",[student_code,name,email,department,year,status,q.params.id],function(e){if(e)return r.status(400).json({message:"Unable to update student"});if(!this.changes)return r.status(404).json({message:"Student not found"});r.json({message:"Student updated"})})});
app.delete("/api/students/:id",auth,(q,r)=>db.run("DELETE FROM students WHERE id=?",[q.params.id],function(e){if(e)return r.status(500).json({message:"Delete failed"});if(!this.changes)return r.status(404).json({message:"Student not found"});r.json({message:"Student deleted"})}));
app.listen(PORT,"0.0.0.0",()=>console.log("CollegeHub backend listening on "+PORT));